name: Clients

on:
  push:
    branches:
      - 'main'
    paths:
      - 'contracts/clients/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'contracts/clients/**'

defaults:
  run:
    working-directory: ./contracts/clients

env:
  NODEJS_VERSION: 16.x

jobs:
  client-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-contracts-clients
      with:
        node-version: ${{ env.NODEJS_VERSION }}
    - run: yarn test
