name: contracts

on:
  push:
    branches:
      - 'main'
    paths:
      - 'contracts/**'
      - '!contracts/clients/**'
  pull_request:
    paths:
      - 'contracts/**'
      - '!contracts/clients/**'

defaults:
  run:
    working-directory: ./contracts

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-contracts-clients
    - run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-contracts-clients
    - run: yarn test

  # ensure gas measurement script runs
  test-gas-measurements:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-contracts-clients
    - uses: ./.github/actions/local-contract-deploy

    - working-directory: ./contracts
      run: ./scripts/wait-for-contract-deploy.sh

    - run: yarn hardhat run ./scripts/measure_gas/run.ts --network gethDev
